PRAGMA foreign_keys=OFF;

CREATE TABLE "new_Player" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "userId" TEXT,
  "firstName" TEXT NOT NULL,
  "lastName" TEXT NOT NULL,
  "nationality" TEXT NOT NULL,
  "gender" TEXT NOT NULL,
  "dominantHand" TEXT NOT NULL,
  "backhand" TEXT NOT NULL,
  "archetype" TEXT NOT NULL,
  "avatar" TEXT NOT NULL,
  "isAi" BOOLEAN NOT NULL DEFAULT false,
  "stats" TEXT NOT NULL,
  "energy" REAL NOT NULL DEFAULT 82,
  "actionEnergy" INTEGER NOT NULL DEFAULT 10,
  "actionEnergyUpdatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "morale" REAL NOT NULL DEFAULT 70,
  "fatigue" REAL NOT NULL DEFAULT 12,
  "health" REAL NOT NULL DEFAULT 95,
  "reputation" REAL NOT NULL DEFAULT 15,
  "budget" INTEGER NOT NULL DEFAULT 5000,
  "gems" INTEGER NOT NULL DEFAULT 0,
  "overall" INTEGER NOT NULL,
  "rankingPoints" INTEGER NOT NULL DEFAULT 0,
  "worldRank" INTEGER NOT NULL DEFAULT 999,
  "fftRanking" TEXT NOT NULL DEFAULT 'NC',
  "fftRankingValidated" BOOLEAN NOT NULL DEFAULT false,
  "amateurPoints" INTEGER NOT NULL DEFAULT 0,
  "careerStage" TEXT NOT NULL DEFAULT 'Amateur',
  "proUnlocked" BOOLEAN NOT NULL DEFAULT false,
  "recentForm" INTEGER NOT NULL DEFAULT 55,
  "wins" INTEGER NOT NULL DEFAULT 0,
  "losses" INTEGER NOT NULL DEFAULT 0,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "Player_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

INSERT INTO "new_Player" (
  "id",
  "userId",
  "firstName",
  "lastName",
  "nationality",
  "gender",
  "dominantHand",
  "backhand",
  "archetype",
  "avatar",
  "isAi",
  "stats",
  "energy",
  "actionEnergy",
  "actionEnergyUpdatedAt",
  "morale",
  "fatigue",
  "health",
  "reputation",
  "budget",
  "gems",
  "overall",
  "rankingPoints",
  "worldRank",
  "fftRanking",
  "fftRankingValidated",
  "amateurPoints",
  "careerStage",
  "proUnlocked",
  "recentForm",
  "wins",
  "losses",
  "createdAt",
  "updatedAt"
)
SELECT
  "id",
  "userId",
  "firstName",
  "lastName",
  "nationality",
  "gender",
  "dominantHand",
  "backhand",
  "archetype",
  "avatar",
  "isAi",
  "stats",
  "energy",
  "actionEnergy",
  "actionEnergyUpdatedAt",
  "morale",
  "fatigue",
  "health",
  "reputation",
  "budget",
  "gems",
  "overall",
  "rankingPoints",
  "worldRank",
  "fftRanking",
  "fftRankingValidated",
  "amateurPoints",
  "careerStage",
  "proUnlocked",
  "recentForm",
  "wins",
  "losses",
  "createdAt",
  "updatedAt"
FROM "Player";

DROP TABLE "Player";
ALTER TABLE "new_Player" RENAME TO "Player";
CREATE UNIQUE INDEX "Player_userId_key" ON "Player"("userId");

PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;
