ALTER TABLE "Player" ADD COLUMN "playerLevel" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "playerXp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "skillPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "spentSkillPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "skillAllocations" TEXT NOT NULL DEFAULT '{}';
